samples: "data/sra_file.txt"

adapters: "resources/adapters/Tru-Seq3-PE.fa"
salmon_index: "resources/genome/salmon_index"
threads: 8

# Keep this if you plan to use tximport
annotation_gtf: "resources/genome/annotation.gtf"
